### ISSUE TITLE
Breaking change in v0.2.1

### ISSUE THREAD

**Issue by krombel** [grokify/go-pkce#1]
When Updating dependency to v0.2.1 the example provided in README does not work anymore:
`pkce.NewCodeVerifier()` should be changed to `pkce.NewCodeVerifier(-1)` to make it work with default length.

Cause is this commit from two years ago which did not make it into a release yet: https://github.com/grokify/go-pkce/commit/7464f5748d2a9cb4bce1a7eb0e80c1defdc64bad

**Comment by grokify** [comment]
Thanks for the issue @krombel!

**Comment by krombel** [comment]
the oauth2 example still shows the old format 😉
